server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 핵심: 요청한 파일이 없으면 index.html로 보냄 (React 라우팅 보호)
        try_files $uri $uri/ /index.html;
    }
}